package edu.upenn.cis555.mustang.peer;

public enum MessageType {
	INDEX,
	REINDEX,
	DOCUMENT_TOTAL_REQUEST,
	DOCUMENT_TOTAL_RESPONSE,
	DOCUMENT_REQUEST,
	DOCUMENT_RESPONSE,
	INVERTED_INDEX_REQUEST,
	INVERTED_INDEX_RESPONSE,
	FORWARD_INDEX_REQUEST,
	FORWARD_INDEX_RESPONSE,
	DIGEST_QUERY,
	DIGEST_RESPONSE,
	LINK,
	RANK,
	SEARCH_QUERY,
	SEARCH_RESULT
}
